In [47]:
from dotenv import load_dotenv
import os
import urllib
from pathlib import Path
import pandas as pd
from sqlalchemy import create_engine
from IPython.display import display, HTML

In [48]:
n_problems = 5
output_filename=r'output\best_params_mean.csv'
best_params_mean_df = pd.read_csv(output_filename)

In [49]:
for problem_number in range(1, n_problems + 1):
    # result_df = best_params_mean_df.loc[best_params_mean_df['problem_number'] == problem_number][columns]
    display(HTML(f"<b style='margin-left:10em; font-size: 20px'>---------Problem {problem_number}---------</b>"))
    display((best_params_mean_df.loc[best_params_mean_df['problem_number'] == problem_number]
                .nsmallest(1, columns=['best_path_len_downtime', 'time_to_run_sec'])))

,problem_number,turbine_order,best_path,best_path_length,best_downtime_days,best_path_len_downtime,time_to_run_sec
537,1,"['BETA-145', 'BETA-153', 'BETA-118', 'BETA-138...","[29, 31, 21, 27, 26, 30, 25, 28, 33, 32, 35, 3...",7.468553,2.479368,9.947921,81.987024

,problem_number,turbine_order,best_path,best_path_length,best_downtime_days,best_path_len_downtime,time_to_run_sec
528,2,"['BETA-48', 'BETA-68', 'BETA-65', 'BETA-80', '...","[6, 8, 7, 9, 10, 11, 20, 14, 12, 13, 15, 19, 1...",4.394326,0.513814,4.90814,18.559051

,problem_number,turbine_order,best_path,best_path_length,best_downtime_days,best_path_len_downtime,time_to_run_sec
62,3,"['BETA-110', 'BETA-109', 'BETA-56', 'BETA-188'...","[6, 5, 3, 14, 13, 8, 9, 10, 11, 7, 12, 15, 0, ...",3.674566,1.603158,5.277724,6.38679

,problem_number,turbine_order,best_path,best_path_length,best_downtime_days,best_path_len_downtime,time_to_run_sec
415,4,"['BETA-108', 'BETA-93', 'BETA-129', 'BETA-120'...","[6, 5, 8, 7, 9, 10, 0, 3, 1, 2, 4, 6]",3.737104,0.94582,4.682924,1.952836

,problem_number,turbine_order,best_path,best_path_length,best_downtime_days,best_path_len_downtime,time_to_run_sec
69,5,"['BETA-58', 'BETA-120', 'BETA-156', 'BETA-201'...","[2, 3, 4, 5, 0, 1, 2]",3.342098,1.263007,4.605105,0.504225

In [50]:
for problem_number in range(1, n_problems + 1):
    # result_df = best_params_mean_df.loc[best_params_mean_df['problem_number'] == problem_number][columns]
    display(HTML(f"<b style='margin-left:10em; font-size: 20px'>---------Problem {problem_number}---------</b>"))
    display((best_params_mean_df.loc[best_params_mean_df['problem_number'] == problem_number]['best_path_len_downtime']
             .round(4)
             .value_counts()
             .sort_index(ascending=True)
             .head(5)))

9.9479     1
9.9525     1
9.9963     1
10.0517    1
10.1472    1
Name: best_path_len_downtime, dtype: int64

4.9081    1
5.0818    1
5.0875    1
5.1022    1
5.1452    1
Name: best_path_len_downtime, dtype: int64

5.2777    2
5.3165    2
5.3306    1
5.3694    1
5.3797    1
Name: best_path_len_downtime, dtype: int64

4.6829    10
4.6911    16
4.7053     4
4.7135     7
4.7534    10
Name: best_path_len_downtime, dtype: int64

4.6051    119
Name: best_path_len_downtime, dtype: int64

In [53]:
for problem_number in range(1, n_problems + 1):
    # result_df = best_params_mean_df.loc[best_params_mean_df['problem_number'] == problem_number][columns]
    display(HTML(f"<b style='margin-left:10em; font-size: 20px'>---------Problem {problem_number}---------</b>"))
    display((best_params_mean_df.loc[best_params_mean_df['problem_number'] == problem_number]
                .nsmallest(20, columns=['best_path_len_downtime']))
                .agg({'time_to_run_sec': 'mean', 'best_path_len_downtime': 'std'}))

time_to_run_sec           58.146496
best_path_len_downtime     0.202453
dtype: float64

time_to_run_sec           15.883031
best_path_len_downtime     0.114068
dtype: float64

time_to_run_sec           11.072421
best_path_len_downtime     0.057917
dtype: float64

time_to_run_sec           2.098494
best_path_len_downtime    0.004188
dtype: float64

time_to_run_sec           6.247592e-01
best_path_len_downtime    9.112518e-16
dtype: float64