In [35]:
from dotenv import load_dotenv
import os
import urllib
from pathlib import Path
import pandas as pd
from sqlalchemy import create_engine
from IPython.display import display, HTML

In [36]:
n_problems = 6
output_filename=r'output\memetic_best_params_mean.csv'
best_params_mean_df = pd.read_csv(output_filename)

In [37]:
for problem_number in range(1, n_problems + 1):
    # result_df = best_params_mean_df.loc[best_params_mean_df['problem_number'] == problem_number][columns]
    display(HTML(f"<b style='margin-left:10em; font-size: 20px'>---------Problem {problem_number}---------</b>"))
    display((best_params_mean_df.loc[best_params_mean_df['problem_number'] == problem_number]
                .nsmallest(1, columns=['best_path_len_downtime', 'time_to_run_sec'])))

,problem_number,turbine_order,best_path,best_path_length,best_downtime_days,best_path_len_downtime,time_to_run_sec
36,1,"['BETA-02', 'BETA-03', 'BETA-09', 'BETA-17', '...","[1, 2, 7, 9, 12, 15, 86, 85, 63, 61, 42, 58, 6...",22.419619,1.872264,24.291883,304.992312

,problem_number,turbine_order,best_path,best_path_length,best_downtime_days,best_path_len_downtime,time_to_run_sec
43,2,"['BETA-184', 'BETA-120', 'BETA-123', 'BETA-153...","[37, 22, 23, 31, 29, 27, 26, 30, 25, 28, 24, 1...",5.903404,2.479368,8.382772,318.87696

,problem_number,turbine_order,best_path,best_path_length,best_downtime_days,best_path_len_downtime,time_to_run_sec
2,3,"['BETA-183', 'BETA-178', 'BETA-167', 'BETA-170...","[20, 19, 16, 17, 18, 0, 4, 1, 3, 2, 5, 6, 8, 7...",4.070715,0.513814,4.584529,10.615426

,problem_number,turbine_order,best_path,best_path_length,best_downtime_days,best_path_len_downtime,time_to_run_sec
3,4,"['BETA-81', 'BETA-110', 'BETA-109', 'BETA-56',...","[4, 6, 5, 3, 14, 13, 8, 9, 10, 11, 7, 12, 15, ...",3.674566,1.603158,5.277724,5.787468

,problem_number,turbine_order,best_path,best_path_length,best_downtime_days,best_path_len_downtime,time_to_run_sec
28,5,"['BETA-152', 'BETA-120', 'BETA-129', 'BETA-93'...","[9, 7, 8, 5, 6, 4, 2, 1, 3, 0, 10, 9]",3.737104,0.94582,4.682924,1.465457

,problem_number,turbine_order,best_path,best_path_length,best_downtime_days,best_path_len_downtime,time_to_run_sec
59,6,"['BETA-58', 'BETA-120', 'BETA-156', 'BETA-201'...","[2, 3, 4, 5, 0, 1, 2]",3.342098,1.263007,4.605105,0.128962

In [38]:
for problem_number in range(1, n_problems + 1):
    # result_df = best_params_mean_df.loc[best_params_mean_df['problem_number'] == problem_number][columns]
    display(HTML(f"<b style='margin-left:10em; font-size: 20px'>---------Problem {problem_number}---------</b>"))
    display((best_params_mean_df.loc[best_params_mean_df['problem_number'] == problem_number]['best_path_len_downtime']
             .round(4)
             .value_counts()
             .sort_index(ascending=True)
             .head(5)))

24.2919    1
27.5227    1
27.7287    1
28.1117    1
28.1466    1
Name: best_path_len_downtime, dtype: int64

8.3828    1
8.4469    1
8.4500    1
8.7312    1
8.7319    1
Name: best_path_len_downtime, dtype: int64

4.5845    5
4.6227    3
4.6518    1
4.7310    1
Name: best_path_len_downtime, dtype: int64

5.2777    10
Name: best_path_len_downtime, dtype: int64

4.6829    10
Name: best_path_len_downtime, dtype: int64

4.6051    10
Name: best_path_len_downtime, dtype: int64

In [39]:
for problem_number in range(1, n_problems + 1):
    # result_df = best_params_mean_df.loc[best_params_mean_df['problem_number'] == problem_number][columns]
    display(HTML(f"<b style='margin-left:10em; font-size: 20px'>---------Problem {problem_number}---------</b>"))
    display((best_params_mean_df.loc[best_params_mean_df['problem_number'] == problem_number]
                .nsmallest(20, columns=['best_path_len_downtime']))
                .agg({'time_to_run_sec': 'mean', 'best_path_len_downtime': 'std'}))

time_to_run_sec           323.114129
best_path_len_downtime      1.450365
dtype: float64

time_to_run_sec           347.503835
best_path_len_downtime      0.280838
dtype: float64

time_to_run_sec           10.077594
best_path_len_downtime     0.046646
dtype: float64

time_to_run_sec           6.908317
best_path_len_downtime    0.000000
dtype: float64

time_to_run_sec           1.95274
best_path_len_downtime    0.00000
dtype: float64

time_to_run_sec           0.238976
best_path_len_downtime    0.000000
dtype: float64