In [33]:
from dotenv import load_dotenv
import os
import urllib
from pathlib import Path
import pandas as pd
from sqlalchemy import create_engine
from IPython.display import display, HTML

In [34]:
algorithm_used = "genetic"
# output_filename=r'output\results_grid_search_2.csv'
output_filename=r'C:\Users\klebi\OneDrive\Documentos\TCC\offshore_ant_web_dev\backend\tests\output\memetic_algo_results_grid_search.csv'

In [35]:
n_problems = 5
final_grid_search_df = pd.read_csv(output_filename)
# final_grid_search_df['tuple_params'] = list(map(tuple, final_grid_search_df[['n_ants', 'alpha', 'beta', 'rho']].values))

In [36]:
min_10_smallest_df = pd.DataFrame()
for problem_number in range(1, n_problems + 1):
    min_10_smallest_df = pd.concat([min_10_smallest_df, 
                                    (final_grid_search_df.loc[final_grid_search_df['problem_number'] == problem_number]
                                    .nsmallest(10, columns=['best_path_len_downtime', 'time_to_run_sec']))])

In [37]:
min_10_smallest_df

,problem_number,turbine_order,best_path,best_path_length,best_downtime_days,best_path_len_downtime,time_to_run_sec,mutation_rate,population_size,number_of_generations,tuple_params
140,1,"['BETA-52', 'BETA-55', 'BETA-182', 'BETA-184',...","[11, 12, 36, 37, 22, 24, 28, 25, 30, 26, 27, 2...",5.442707,1.239684,6.682391,375.944849,0.2,100,40,"(0.2, 100.0, 40.0)"
95,1,"['BETA-149', 'BETA-135', 'BETA-141', 'BETA-123...","[30, 25, 28, 23, 32, 33, 34, 35, 40, 38, 1, 39...",5.925745,1.239684,7.165429,884.836560,0.1,200,50,"(0.1, 200.0, 50.0)"
60,1,"['BETA-120', 'BETA-184', 'BETA-55', 'BETA-52',...","[22, 37, 12, 11, 9, 39, 38, 0, 1, 8, 3, 2, 7, ...",6.002886,1.239684,7.242570,403.940226,0.1,150,30,"(0.1, 150.0, 30.0)"
45,1,"['BETA-45', 'BETA-20', 'BETA-18', 'BETA-25', '...","[10, 5, 4, 6, 7, 2, 3, 1, 8, 0, 37, 36, 12, 11...",6.022124,1.239684,7.261808,385.088080,0.1,100,50,"(0.1, 100.0, 50.0)"
55,1,"['BETA-184', 'BETA-182', 'BETA-52', 'BETA-55',...","[37, 36, 11, 12, 10, 13, 20, 19, 18, 17, 14, 1...",6.099864,1.239684,7.339549,212.688798,0.1,150,20,"(0.1, 150.0, 20.0)"
145,1,"['BETA-65', 'BETA-82', 'BETA-84', 'BETA-85', '...","[14, 17, 18, 19, 20, 13, 24, 28, 25, 30, 26, 2...",6.195094,1.239684,7.434778,417.327806,0.2,100,50,"(0.2, 100.0, 50.0)"
70,1,"['BETA-52', 'BETA-182', 'BETA-198', 'BETA-205'...","[11, 36, 38, 39, 9, 7, 2, 3, 8, 1, 0, 40, 34, ...",6.210320,1.239684,7.450004,658.809415,0.1,150,50,"(0.1, 150.0, 50.0)"
85,1,"['BETA-172', 'BETA-174', 'BETA-212', 'Doca', '...","[34, 35, 40, 0, 39, 11, 12, 9, 1, 8, 2, 3, 7, ...",6.249775,1.239684,7.489459,410.069644,0.1,200,30,"(0.1, 200.0, 30.0)"
65,1,"['BETA-05', 'BETA-09', 'BETA-33', 'BETA-01', '...","[2, 3, 8, 1, 0, 38, 39, 9, 11, 12, 36, 34, 35,...",6.279968,1.239684,7.519653,500.329809,0.1,150,40,"(0.1, 150.0, 40.0)"
90,1,"['BETA-138', 'BETA-137', 'BETA-149', 'BETA-135...","[27, 26, 30, 25, 28, 23, 21, 22, 24, 12, 39, 8...",6.325612,1.239684,7.565297,656.151549,0.1,200,40,"(0.1, 200.0, 40.0)"
301,2,"['BETA-39', 'Doca', 'BETA-172', 'BETA-170', 'B...","[4, 0, 18, 17, 16, 19, 20, 13, 15, 14, 12, 11,...",4.070715,0.256907,4.327622,19.045262,0.4,50,10,"(0.4, 50.0, 10.0)"
101,2,"['BETA-48', 'BETA-47', 'BETA-22', 'BETA-25', '...","[6, 5, 2, 3, 1, 4, 0, 18, 17, 16, 19, 20, 13, ...",4.070715,0.256907,4.327622,19.120105,0.2,50,10,"(0.2, 50.0, 10.0)"
201,2,"['BETA-183', 'BETA-122', 'BETA-144', 'BETA-124...","[20, 13, 15, 14, 12, 11, 10, 9, 7, 8, 6, 5, 2,...",4.070715,0.256907,4.327622,19.261016,0.3,50,10,"(0.3, 50.0, 10.0)"
426,2,"['BETA-114', 'BETA-107', 'BETA-80', 'BETA-65',...","[11, 10, 9, 7, 8, 6, 5, 2, 3, 1, 4, 0, 18, 17,...",4.070715,0.256907,4.327622,27.435210,0.5,100,10,"(0.5, 100.0, 10.0)"
226,2,"['BETA-80', 'BETA-107', 'BETA-114', 'BETA-121'...","[9, 10, 11, 12, 14, 15, 13, 20, 19, 16, 17, 18...",4.070715,0.256907,4.327622,31.202128,0.3,100,10,"(0.3, 100.0, 10.0)"
126,2,"['BETA-107', 'BETA-80', 'BETA-65', 'BETA-68', ...","[10, 9, 7, 8, 6, 5, 2, 3, 1, 4, 0, 18, 17, 16,...",4.070715,0.256907,4.327622,34.217689,0.2,100,10,"(0.2, 100.0, 10.0)"
26,2,"['BETA-22', 'BETA-47', 'BETA-48', 'BETA-68', '...","[2, 5, 6, 8, 7, 9, 10, 11, 12, 14, 15, 13, 20,...",4.070715,0.256907,4.327622,37.171231,0.1,100,10,"(0.1, 100.0, 10.0)"
406,2,"['BETA-122', 'BETA-183', 'BETA-178', 'BETA-167...","[13, 20, 19, 16, 17, 18, 0, 4, 1, 3, 2, 5, 6, ...",4.070715,0.256907,4.327622,41.278163,0.5,50,20,"(0.5, 50.0, 20.0)"
451,2,"['BETA-170', 'BETA-167', 'BETA-178', 'BETA-183...","[17, 16, 19, 20, 13, 15, 14, 12, 11, 10, 9, 7,...",4.070715,0.256907,4.327622,44.800089,0.5,150,10,"(0.5, 150.0, 10.0)"
206,2,"['BETA-170', 'BETA-172', 'Doca', 'BETA-39', 'B...","[17, 18, 0, 4, 1, 3, 2, 5, 6, 8, 7, 9, 10, 11,...",4.070715,0.256907,4.327622,45.638233,0.3,50,20,"(0.3, 50.0, 20.0)"
202,3,"['BETA-110', 'BETA-109', 'BETA-56', 'BETA-188'...","[6, 5, 3, 14, 13, 8, 9, 10, 11, 7, 12, 15, 0, ...",3.674566,0.801579,4.476145,11.759571,0.3,50,10,"(0.3, 50.0, 10.0)"
102,3,"['BETA-109', 'BETA-56', 'BETA-188', 'BETA-182'...","[5, 3, 14, 13, 8, 9, 10, 11, 7, 12, 15, 0, 1, ...",3.674566,0.801579,4.476145,11.987824,0.2,50,10,"(0.2, 50.0, 10.0)"
107,3,"['BETA-110', 'BETA-109', 'BETA-56', 'BETA-188'...","[6, 5, 3, 14, 13, 8, 9, 10, 11, 7, 12, 15, 0, ...",3.674566,0.801579,4.476145,21.253658,0.2,50,20,"(0.2, 50.0, 20.0)"
27,3,"['BETA-109', 'BETA-56', 'BETA-188', 'BETA-182'...","[5, 3, 14, 13, 8, 9, 10, 11, 7, 12, 15, 0, 1, ...",3.674566,0.801579,4.476145,21.573751,0.1,100,10,"(0.1, 100.0, 10.0)"
207,3,"['BETA-110', 'BETA-109', 'BETA-56', 'BETA-188'...","[6, 5, 3, 14, 13, 8, 9, 10, 11, 7, 12, 15, 0, ...",3.674566,0.801579,4.476145,22.149211,0.3,50,20,"(0.3, 50.0, 20.0)"
327,3,"['BETA-109', 'BETA-56', 'BETA-188', 'BETA-182'...","[5, 3, 14, 13, 8, 9, 10, 11, 7, 12, 15, 0, 1, ...",3.674566,0.801579,4.476145,22.375815,0.4,100,10,"(0.4, 100.0, 10.0)"
307,3,"['BETA-109', 'BETA-56', 'BETA-188', 'BETA-182'...","[5, 3, 14, 13, 8, 9, 10, 11, 7, 12, 15, 0, 1, ...",3.674566,0.801579,4.476145,24.234246,0.4,50,20,"(0.4, 50.0, 20.0)"
12,3,"['BETA-110', 'BETA-109', 'BETA-56', 'BETA-188'...","[6, 5, 3, 14, 13, 8, 9, 10, 11, 7, 12, 15, 0, ...",3.674566,0.801579,4.476145,25.977962,0.1,50,30,"(0.1, 50.0, 30.0)"
152,3,"['BETA-110', 'BETA-109', 'BETA-56', 'BETA-188'...","[6, 5, 3, 14, 13, 8, 9, 10, 11, 7, 12, 15, 0, ...",3.674566,0.801579,4.476145,31.019316,0.2,150,10,"(0.2, 150.0, 10.0)"
7,3,"['BETA-109', 'BETA-56', 'BETA-188', 'BETA-182'...","[5, 3, 14, 13, 8, 9, 10, 11, 7, 12, 15, 0, 1, ...",3.674566,0.801579,4.476145,34.782468,0.1,50,20,"(0.1, 50.0, 20.0)"
3,4,"['BETA-30', 'BETA-11', 'BETA-15', 'BETA-73', '...","[3, 1, 2, 4, 6, 5, 8, 7, 9, 10, 0, 3]",3.737104,0.472910,4.210014,2.630264,0.1,50,10,"(0.1, 50.0, 10.0)"
103,4,"['BETA-73', 'BETA-15', 'BETA-11', 'BETA-30', '...","[4, 2, 1, 3, 0, 10, 9, 7, 8, 5, 6, 4]",3.737104,0.472910,4.210014,2.637457,0.2,50,10,"(0.2, 50.0, 10.0)"
203,4,"['BETA-93', 'BETA-108', 'BETA-73', 'BETA-15', ...","[5, 6, 4, 2, 1, 3, 0, 10, 9, 7, 8, 5]",3.737104,0.472910,4.210014,3.397480,0.3,50,10,"(0.3, 50.0, 10.0)"
303,4,"['BETA-120', 'BETA-129', 'BETA-93', 'BETA-108'...","[7, 8, 5, 6, 4, 2, 1, 3, 0, 10, 9, 7]",3.737104,0.472910,4.210014,3.498947,0.4,50,10,"(0.4, 50.0, 10.0)"
403,4,"['BETA-73', 'BETA-15', 'BETA-11', 'BETA-30', '...","[4, 2, 1, 3, 0, 10, 9, 7, 8, 5, 6, 4]",3.737104,0.472910,4.210014,3.834893,0.5,50,10,"(0.5, 50.0, 10.0)"
208,4,"['BETA-152', 'BETA-120', 'BETA-129', 'BETA-93'...","[9, 7, 8, 5, 6, 4, 2, 1, 3, 0, 10, 9]",3.737104,0.472910,4.210014,4.103251,0.3,50,20,"(0.3, 50.0, 20.0)"
128,4,"['Doca', 'BETA-30', 'BETA-11', 'BETA-15', 'BET...","[0, 3, 1, 2, 4, 6, 5, 8, 7, 9, 10, 0]",3.737104,0.472910,4.210014,5.763324,0.2,100,10,"(0.2, 100.0, 10.0)"
108,4,"['BETA-201', 'Doca', 'BETA-30', 'BETA-11', 'BE...","[10, 0, 3, 1, 2, 4, 6, 5, 8, 7, 9, 10]",3.737104,0.472910,4.210014,5.850563,0.2,50,20,"(0.2, 50.0, 20.0)"
28,4,"['BETA-120', 'BETA-129', 'BETA-93', 'BETA-108'...","[7, 8, 5, 6, 4, 2, 1, 3, 0, 10, 9, 7]",3.737104,0.472910,4.210014,6.021191,0.1,100,10,"(0.1, 100.0, 10.0)"
228,4,"['BETA-129', 'BETA-93', 'BETA-108', 'BETA-73',...","[8, 5, 6, 4, 2, 1, 3, 0, 10, 9, 7, 8]",3.737104,0.472910,4.210014,6.359264,0.3,100,10,"(0.3, 100.0, 10.0)"
4,5,"['BETA-58', 'BETA-120', 'BETA-156', 'BETA-201'...","[2, 3, 4, 5, 0, 1, 2]",3.342098,0.631503,3.973602,0.237063,0.1,50,10,"(0.1, 50.0, 10.0)"
104,5,"['BETA-58', 'BETA-120', 'BETA-156', 'BETA-201'...","[2, 3, 4, 5, 0, 1, 2]",3.342098,0.631503,3.973602,0.279032,0.2,50,10,"(0.2, 50.0, 10.0)"
204,5,"['BETA-58', 'BETA-120', 'BETA-156', 'BETA-201'...","[2, 3, 4, 5, 0, 1, 2]",3.342098,0.631503,3.973602,0.296945,0.3,50,10,"(0.3, 50.0, 10.0)"
304,5,"['BETA-58', 'BETA-120', 'BETA-156', 'BETA-201'...","[2, 3, 4, 5, 0, 1, 2]",3.342098,0.631503,3.973602,0.309210,0.4,50,10,"(0.4, 50.0, 10.0)"
404,5,"['BETA-58', 'BETA-120', 'BETA-156', 'BETA-201'...","[2, 3, 4, 5, 0, 1, 2]",3.342098,0.631503,3.973602,0.328555,0.5,50,10,"(0.5, 50.0, 10.0)"
29,5,"['BETA-58', 'BETA-120', 'BETA-156', 'BETA-201'...","[2, 3, 4, 5, 0, 1, 2]",3.342098,0.631503,3.973602,0.486176,0.1,100,10,"(0.1, 100.0, 10.0)"
129,5,"['BETA-58', 'BETA-120', 'BETA-156', 'BETA-201'...","[2, 3, 4, 5, 0, 1, 2]",3.342098,0.631503,3.973602,0.531431,0.2,100,10,"(0.2, 100.0, 10.0)"
229,5,"['BETA-58', 'BETA-120', 'BETA-156', 'BETA-201'...","[2, 3, 4, 5, 0, 1, 2]",3.342098,0.631503,3.973602,0.548305,0.3,100,10,"(0.3, 100.0, 10.0)"
209,5,"['BETA-58', 'BETA-120', 'BETA-156', 'BETA-201'...","[2, 3, 4, 5, 0, 1, 2]",3.342098,0.631503,3.973602,0.549157,0.3,50,20,"(0.3, 50.0, 20.0)"
109,5,"['BETA-58', 'BETA-120', 'BETA-156', 'BETA-201'...","[2, 3, 4, 5, 0, 1, 2]",3.342098,0.631503,3.973602,0.553611,0.2,50,20,"(0.2, 50.0, 20.0)"

In [38]:
if algorithm_used in ["genetic", "memetic"]:
    columns = ['best_path_len_downtime', 'time_to_run_sec', 'mutation_rate', 'population_size', 'number_of_generations']
else:
    columns = ['best_path_len_downtime', 'time_to_run_sec', 'n_ants', 'alpha', 'beta', 'rho']

for problem_number in range(1, n_problems + 1):
    result_df = min_10_smallest_df.loc[min_10_smallest_df['problem_number'] == problem_number][columns]
    display(HTML(f"<b style='margin-left:10em; font-size: 20px'>---------Problem {problem_number}---------</b>"))
    display(result_df)

    if algorithm_used == "genetic":
        display(result_df.agg({'best_path_len_downtime': 'median', 'time_to_run_sec': 'median', 
                                'mutation_rate': lambda x: x.mode().iloc[0], 'population_size': lambda x: x.mode().iloc[0], 'number_of_generations': lambda x: x.mode().iloc[0]}).to_frame().T)
    else:
        display(result_df.agg({'best_path_len_downtime': 'min', 'time_to_run_sec': 'min', 
                    'n_ants': 'mean', 'alpha': 'mean', 'beta': 'mean', 'rho': 'mean'}).to_frame().T)

,best_path_len_downtime,time_to_run_sec,mutation_rate,population_size,number_of_generations
140,6.682391,375.944849,0.2,100,40
95,7.165429,884.836560,0.1,200,50
60,7.242570,403.940226,0.1,150,30
45,7.261808,385.088080,0.1,100,50
55,7.339549,212.688798,0.1,150,20
145,7.434778,417.327806,0.2,100,50
70,7.450004,658.809415,0.1,150,50
85,7.489459,410.069644,0.1,200,30
65,7.519653,500.329809,0.1,150,40
90,7.565297,656.151549,0.1,200,40

,best_path_len_downtime,time_to_run_sec,mutation_rate,population_size,number_of_generations
0,7.387163,413.698725,0.1,150.0,50.0

,best_path_len_downtime,time_to_run_sec,mutation_rate,population_size,number_of_generations
301,4.327622,19.045262,0.4,50,10
101,4.327622,19.120105,0.2,50,10
201,4.327622,19.261016,0.3,50,10
426,4.327622,27.435210,0.5,100,10
226,4.327622,31.202128,0.3,100,10
126,4.327622,34.217689,0.2,100,10
26,4.327622,37.171231,0.1,100,10
406,4.327622,41.278163,0.5,50,20
451,4.327622,44.800089,0.5,150,10
206,4.327622,45.638233,0.3,50,20

,best_path_len_downtime,time_to_run_sec,mutation_rate,population_size,number_of_generations
0,4.327622,32.709908,0.3,50.0,10.0

,best_path_len_downtime,time_to_run_sec,mutation_rate,population_size,number_of_generations
202,4.476145,11.759571,0.3,50,10
102,4.476145,11.987824,0.2,50,10
107,4.476145,21.253658,0.2,50,20
27,4.476145,21.573751,0.1,100,10
207,4.476145,22.149211,0.3,50,20
327,4.476145,22.375815,0.4,100,10
307,4.476145,24.234246,0.4,50,20
12,4.476145,25.977962,0.1,50,30
152,4.476145,31.019316,0.2,150,10
7,4.476145,34.782468,0.1,50,20

,best_path_len_downtime,time_to_run_sec,mutation_rate,population_size,number_of_generations
0,4.476145,22.262513,0.1,50.0,10.0

,best_path_len_downtime,time_to_run_sec,mutation_rate,population_size,number_of_generations
3,4.210014,2.630264,0.1,50,10
103,4.210014,2.637457,0.2,50,10
203,4.210014,3.397480,0.3,50,10
303,4.210014,3.498947,0.4,50,10
403,4.210014,3.834893,0.5,50,10
208,4.210014,4.103251,0.3,50,20
128,4.210014,5.763324,0.2,100,10
108,4.210014,5.850563,0.2,50,20
28,4.210014,6.021191,0.1,100,10
228,4.210014,6.359264,0.3,100,10

,best_path_len_downtime,time_to_run_sec,mutation_rate,population_size,number_of_generations
0,4.210014,3.969072,0.2,50.0,10.0

,best_path_len_downtime,time_to_run_sec,mutation_rate,population_size,number_of_generations
4,3.973602,0.237063,0.1,50,10
104,3.973602,0.279032,0.2,50,10
204,3.973602,0.296945,0.3,50,10
304,3.973602,0.309210,0.4,50,10
404,3.973602,0.328555,0.5,50,10
29,3.973602,0.486176,0.1,100,10
129,3.973602,0.531431,0.2,100,10
229,3.973602,0.548305,0.3,100,10
209,3.973602,0.549157,0.3,50,20
109,3.973602,0.553611,0.2,50,20

,best_path_len_downtime,time_to_run_sec,mutation_rate,population_size,number_of_generations
0,3.973602,0.407366,0.2,50.0,10.0

In [39]:
# min_10_smallest_df.to_csv(r'output/smallest_results.csv', index=False)